# Generated by Django 5.2.4 on 2025-09-24 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('target_co2_reduction', models.DecimalField(decimal_places=2, help_text='Target CO2 reduction value for this product.', max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='BatchMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.material')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('materials', models.ManyToManyField(through='production_planner.BatchMaterial', to='inventory.material')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production_planner.product')),
            ],
        ),
        migrations.AddField(
            model_name='batchmaterial',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production_planner.productionbatch'),
        ),
        migrations.AlterUniqueTogether(
            name='batchmaterial',
            unique_together={('batch', 'material')},
        ),
    ]
